### ISSUE TITLE
IT新人，针对脚本检测ipv4地址问题

### ISSUE THREAD

**Issue by forgetfun** [oneclickvirt/6in4#1]
想将脚本应用于AWS lightsail 上，创建SIT隧道与fortinet vpn一起使用。因为lightsail在vm内部使用的是私有IP，在跑完脚本后提示的服务端IPV4为vm私有段IP，请问这种状态下client -server 的隧道可以正常建立吗？还是说IPV4地址需要直接attach到服务器的网卡上？假如需要直接在网卡上pppoe后ppp接口上的地址可以作为服务端的IPV4地址使用吗？

**Comment by spiritLHLS** [comment]
通信的IP两端都能ping的通就行

**Comment by forgetfun** [comment]
感谢回复，隧道已经创建好了。我可以从fortinet vpn上ping通服务器的ipv6地址，但是无法ping通其他ipv6地址，还想请问是否是ndpresponder配置的问题。另想请问脚本第361行 new_exec_start="ExecStart=/usr/local/bin/ndpresponder -i ${interface} -n ${ipv6_address_without_last_segment}【】/${ipv6_prefixlen}" 加【】的这个位置是否缺少了一个“:”？

**Comment by spiritLHLS** [comment]
不是你想的那个问题

https://github.com/oneclickvirt/6in4/blob/main/6in4.sh#L525

感觉上可能是你的路由冲突/IPV6不通，没有其他相关信息我无法判断是什么问题

**Comment by forgetfun** [comment]
感谢回复，因为在跑脚本的时候，到启动ndpresponder 这边就会报错，提示：
Created symlink /etc/systemd/system/multi-user.target.wants/ndpresponder.service → /etc/systemd/system/ndpresponder.service.
● ndpresponder.service - NDPPD Daemon
     Loaded: loaded (/etc/systemd/system/ndpresponder.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2023-12-19 03:29:42 UTC; 11ms ago
    Process: 2056 ExecStart=/usr/local/bin/ndpresponder -i ens5 -n 2406:da18:2ae:c500:ba48:ab0e:3103:/128 (code=exited, status=1/FAILURE)
   Main PID: 2056 (code=exited, status=1/FAILURE)

**Comment by spiritLHLS** [comment]
只有/128？那你隧道不了任何东西，你的服务器只有一个IPV6地址

**Comment by spiritLHLS** [comment]
如果需要隧道分配V6地址到别的服务器上，至少需要/112大小的子网掩码，一般我这使用/64子网分一个/80到别的服务器上
