### ISSUE TITLE
Please help, I get nothing when trying this method.

### ISSUE THREAD

**Issue by firestarter7924** [oneclickvirt/6in4#2]
Hello
First, thanks for your work
I have VPS with IPV6 /56 under Ubuntu 22.04 and home PC. I use tunnel from hurricane and wanna use my own 6in4 tunnel. Then i tried your scrypt.  And i got nothing.  Please help.
This is installatiobn log, that is all what i have, there is no server log or client log...

Will use gre protocol for ipv6 tunnel creation
将使用gre协议进行ipv6隧道创建
脚本当天运行次数:8，累计运行次数:1340
Updating package management sources
Installing dos2unix
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  dos2unix
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 384 kB of archives.
After this operation, 1367 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 dos2unix amd64 7.4.2-2 [384 kB]
Fetched 384 kB in 0s (1845 kB/s)
Selecting previously unselected package dos2unix.
(Reading database ... 106410 files and directories currently installed.)
Preparing to unpack .../dos2unix_7.4.2-2_amd64.deb ...
Unpacking dos2unix (7.4.2-2) ...
Setting up dos2unix (7.4.2-2) ...
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.5.0-21-generic
NEEDRESTART-KEXP: 6.5.0-21-generic
NEEDRESTART-KSTA: 1
Installing ipcalc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ipcalc
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 25.4 kB of archives.
After this operation, 73.7 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ipcalc all 0.42-2 [25.4 kB]
Fetched 25.4 kB in 0s (275 kB/s)
Selecting previously unselected package ipcalc.
(Reading database ... 106509 files and directories currently installed.)
Preparing to unpack .../archives/ipcalc_0.42-2_all.deb ...
Unpacking ipcalc (0.42-2) ...
Setting up ipcalc (0.42-2) ...
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.5.0-21-generic
NEEDRESTART-KEXP: 6.5.0-21-generic
NEEDRESTART-KSTA: 1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
iproute2 is already the newest version (5.15.0-1ubuntu2).
iproute2 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
net-tools is already the newest version (1.60+git20181103.0eebece-1ubuntu5).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
IP area being detected ......
CDN available, using CDN
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openssl is already the newest version (3.0.2-0ubuntu1.14).
openssl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
This step will take about 1 minute, please be patient.
在此步骤中将停留约 1 分钟，请耐心等待
root@xxx:~# systemctl status ndpresponder
Unit ndpresponder.service could not be found.

**Comment by spiritLHLS** [comment]
![图片](https://github.com/oneclickvirt/6in4/assets/103393591/037905e3-ce71-4a0e-b64b-a194fa5a4ea7)
![图片](https://github.com/oneclickvirt/6in4/assets/103393591/c5ebd84f-1dc6-494b-b799-b10fe89464af)
![图片](https://github.com/oneclickvirt/6in4/assets/103393591/50cca01b-b81f-44f0-b02e-d365a426a14f)
In fact you should see an output log similar to the one above.
It seems to me that my project can't recognise your IPV6 subnet, recognising it as a non-creatable tunnel situation now.
You may need to run the following command on your Ubuntu to ensure that your IPV6 subnet is available:

```
curl -L https://raw.githubusercontent.com/spiritLHLS/ecs/main/archive/eo6s.sh -o eo6s.sh && chmod +x eo6s.sh && bash eo6s.sh
```

**Comment by firestarter7924** [comment]
![Без имени](https://github.com/oneclickvirt/6in4/assets/47260646/c0cc3448-ddee-4a6f-9f5f-b03d443394cc)

**Comment by spiritLHLS** [comment]
Ok, this confirms that the subnet is available. 
Now I've added a new piece of code to the script https://github.com/oneclickvirt/6in4/blob/main/6in4.sh#L306
so you can re-download the script and run it and see if there's any line that's not outputting like:

```
    echo "ipv6_address: $ipv6_address"
    echo "ipv6_prefixlen: $ipv6_prefixlen"
    echo "ipv6_gateway: $ipv6_gateway"
    echo "ipv6_address_without_last_segment: $ipv6_address_without_last_segment"
    echo "interface: $interface" 
    echo "ipv4_address: $ipv4_address" 
    echo "ipv4_prefixlen: $ipv4_prefixlen" 
    echo "ipv4_gateway: $ipv4_gateway" 
    echo "ipv4_subnet: $ipv4_subnet"
```

**Comment by firestarter7924** [comment]
now it works, thanks
![Без имени1](https://github.com/oneclickvirt/6in4/assets/47260646/92bb388c-042d-431b-a1f6-d5e8ce81d3b4)

**Comment by spiritLHLS** [comment]
> now it works, thanks ![Без имени1](https://private-user-images.githubusercontent.com/47260646/307576015-92bb388c-042d-431b-a1f6-d5e8ce81d3b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDg2MTcsIm5iZiI6MTcwODg0ODMxNywicGF0aCI6Ii80NzI2MDY0Ni8zMDc1NzYwMTUtOTJiYjM4OGMtMDQyZC00MzFiLWExZjYtZDVlOGNlODFkM2I0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA4MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ODVkMGEzMDQ4ZGZhOWU1ZDRmZTNjMjQ1MmYxZjYyMTdiNGFjZjRiMjI3MDI1ZDk4ZGNmMjgxZjRlMjBjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ho9bPoCa3nZMhySBZQ3m6Fl7lMrRouD1qu1-WwNUDz0)

Is there any value whose output is empty? That is, which is the line with no content after the colon? There should be at least one value that is empty causing your problem

**Comment by spiritLHLS** [comment]
As per the diagram you showed, I seem to see that the value of ipv6_gateway is empty.
```
cat /usr/local/bin/6in4_ipv6_gateway
```

**Comment by firestarter7924** [comment]
cat /usr/local/bin/6in4_ipv6_gateway
got nothing...

**Comment by spiritLHLS** [comment]
Found the problem, my project didn't recognise your IPV6 gateway, so the subsequent tunnel setup etc. couldn't be executed, I need you to run the following commands again to see what output you get

```
ip -6 route show | awk '/default via/{print $3}'
```

To avoid privacy breaches, you can code everything after the first decimal point. For example, for 8.7.6.5, I only need to know the 8 part of it.

> cat /usr/local/bin/6in4_ipv6_gateway got nothing...

**Comment by firestarter7924** [comment]
![image](https://github.com/oneclickvirt/6in4/assets/47260646/8b929a93-f874-463e-b4d5-5f325c50fb1e)
Nothing

**Comment by spiritLHLS** [comment]
```
ip -6 route show
```

> ![image](https://private-user-images.githubusercontent.com/47260646/307596771-8b929a93-f874-463e-b4d5-5f325c50fb1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzAxNTIsIm5iZiI6MTcwODg2OTg1MiwicGF0aCI6Ii80NzI2MDY0Ni8zMDc1OTY3NzEtOGI5MjlhOTMtZjg3NC00NjNlLWI0ZDUtNWYzMjVjNTBmYjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE0MDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzM2RjMmY3ZmU1NWJmODQ0MTMwY2VhMzczMDlhZTQ5N2JkYzM5MTViYWIzZDZmMjk3MTU1ZjliMDA5ZjVkNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jTpDBWNYkQ0XOBgtP4RK1fIXqS014kl5fMGt_IbZ4Bk) Nothing

**Comment by firestarter7924** [comment]
![Без имени2](https://github.com/oneclickvirt/6in4/assets/47260646/4db02bac-b296-4120-a66f-6d6439122399)

**Comment by spiritLHLS** [comment]
![图片](https://github.com/oneclickvirt/6in4/assets/103393591/09120170-059a-4ca5-b155-a895c6440a1a)
It looks like I need a patch to detect the writing of gateway for IPV6 in another format, which is currently the only format my command recognises.

**Comment by firestarter7924** [comment]
will wait.. thanks.

**Comment by spiritLHLS** [comment]
> will wait.. thanks.

Adapting multiple network interfaces is not universal, I'll write later in the note that if you encounter multiple network interfaces, you can solve the problem yourself by manually writing the IPV6 gateway in the /usr/local/bin/6in4_ipv6_gateway file.

For you, it's the IPV6 address after writing to nexthop.
