### ISSUE TITLE
报错了 404

### ISSUE THREAD

**Issue by KunBuFenZi** [oneclickvirt/6in4#3]
--2024-06-13 16:50:00--  https://cdn0.spiritlhl.top/https://raw.githubusercontent.com/spiritLHLS/pve/main/extra_scripts/ndpresponder.service
Resolving cdn0.spiritlhl.top (cdn0.spiritlhl.top)... 172.67.208.154, 104.21.66.226
Connecting to cdn0.spiritlhl.top (cdn0.spiritlhl.top)|172.67.208.154|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-06-13 16:50:02 ERROR 404: Not Found.

Failed to start ndpresponder.service: Unit ndpresponder.service is masked.
Failed to enable unit: Unit file /etc/systemd/system/ndpresponder.service is masked.
○ ndpresponder.service
     Loaded: masked (Reason: Unit ndpresponder.service is masked.)
     Active: inactive (dead)

**Comment by spiritLHLS** [comment]
哦哦哦，忘了仓库换地址这个没换，我改一下，等等

**Comment by spiritLHLS** [comment]
https://github.com/oneclickvirt/6in4/commit/facddaaf61ddd2fde42d90f46368c96bb833baee

已修复，你看看
