### ISSUE TITLE
Large prefix causes error

### ISSUE THREAD

**Issue by amanjuman** [oneclickvirt/6in4#4]
./6in4.sh: line 284: 2a07: value too great for base (error token is "2a07")
The difference between the size of the cut molecular net and the original subnet is detected to be greater than 2 to the 16th power
so the size of the molecular net to be cut is modified to be /
检测到切分子网和原始子网大小差值大于2的16次方，故而修改要切分子网为 /
This step will take about 1 minute, please be patient.
在此步骤中将停留约 1 分钟，请耐心等待

**Comment by spiritLHLS** [comment]
How big is your initial subnet?

**Comment by spiritLHLS** [comment]
https://github.com/oneclickvirt/6in4/commit/0458cc83dd9afe532defd2d830cfeebd9f6f5f56

Try fix, wait your test
